# golangci-lint configuration
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - exportloopref
    - whitespace

  disable:
    - deadcode
    - structcheck
    - varcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: poxy

  misspell:
    locale: US

  gosec:
    excludes:
      - G204 # Subprocess launched with a potential tainted input
      - G304 # File path provided as taint input

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - noctx

    - path: cmd/
      linters:
        - gocyclo

  max-issues-per-linter: 50
  max-same-issues: 10
